config/routes.rb
Rails.application.routes.draw do

  resources :categories

  resources :users do
    resources :posts,
    only: [:index, :new, :create]
    resources :comments, only: [ :index, :destroy ]
  end

  resources :posts, only: [:show, :edit, :update, :destroy] do
    resources :votes, only: [:create]
    resources :comments, only: [:create, :destroy ], module: :posts
  end

  resources :comments, only: [ :create, :destroy ] do
    resources :comments, only: [:create, :destroy ], module: :comments
  end

  get 'posts', to: 'posts#all'

  root 'welcome#index'

  get 'login', to: 'sessions#login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DS+L available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
end

app/controllers/comments/comments_controller.rb
class Comments::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
    @commentable = Comment.find(params[:comment_id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @user = User.find(params[:user_id])
    @comments = @user.comments.order("created_at desc")

    if @comments.count == 0
      redirect_to user_path(@user)
      flash[:danger] = "No comments available to see."
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    redirect_to posts_path
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @commentable.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html {
          redirect_to :back, notice: 'Comment was successfully created.'
        }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render @post}
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end


  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
    @commentable = Post.find(params[:post_id])
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
    <li class="list-group-item thread">
      <div class="media">

        <div class="media-body">
          <div class="pull-right">



                        <% if comments.user == current_user %>
                          <div class="btn-group pull-right">
                            <%= link_to "Delete", comment_comment_path(comments, comments), method: :delete,
                                                  data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-xs" %>

                            
                          </div>
                        <% end %>
          </div>
          <div class="media-heading">
            <h4>
              <%= link_to user_path(comments.user) do %>
                <span class="label label-<%= logged_in? && (comments.user_id == current_user.id) ? "primary" : "default" %>">
                  <%= comments.user.username %>
                </span>
              <% end %>
            <small>
              &nbsp; <%= time_ago_in_words(comments.created_at).capitalize %> ago
            </small>
            </h4>

          </div>

          <%= comments.body %>


          <div class="goo">

            <% if logged_in? %>

              <span class="toggle-reply">Reply</span>
              <div class="reply-toggle">
                <span class="label label-<%= logged_in? && (comments.user_id == current_user.id) ? "primary" : "default" %>">
                  <%= current_user.username %>
                </span><%= render partial: "comments/form", locals: { commentable: comments } %>
              </div>
            <br/>
            <% else %>
              <h3>Please log in to make a comment.</h3>

            <% end %>

          </div>

        </div>

      </div>
      <% if comments.comments.any? %>
      <ul class="list-group">
        <%= render partial: "comments/comments", collection: comments.comments %>
      </ul>
      <% end %>

    </li>

app/views/comments/_form.html.erb
<!-- form to make comments on post -->
<%= form_for([commentable, Comment.new], html: {class: "form-inline"}) do |c| %>
  <% if Comment.new.errors.any? %>
    <div class="well well-danger">
      <h2><%= pluralize(Comment.new.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% Comment.new.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= c.text_field :body, col: 4 ,class: "form-control", placeholder: "Enter a comment" %>
  </div>
  <div class="form-group">
    <%= c.submit "Post", class: "btn btn-success " %>
  </div>
<% end %>
<!-- end form -->

app/views/comments/index.html.erb
<div class="container">
  <div class="row">

      <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <ul class="list-group">
          <% @comments.each do |comments| %>
          <li class="list-group-item thread">
            <div class="media">

              <div class="media-body">
                <div class="pull-right">



                              <% if comments.user == current_user %>
                                <div class="btn-group pull-right">
                                  <%= link_to "Delete", comment_comment_path(comments, comments), method: :delete,
                                                        data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-xs" %>


                                </div>
                              <% end %>
                </div>
                <div class="media-heading">
                  <h4>
                    <%= link_to user_path(comments.user) do %>
                      <span class="label label-<%= logged_in? && (comments.user_id == current_user.id) ? "primary" : "default" %>">
                        <%= comments.user.username %>
                      </span>
                    <% end %>
                  <small>
                    &nbsp; <%= time_ago_in_words(comments.created_at).capitalize %> ago
                  </small>
                  </h4>

                </div>

                <%= comments.body %>



              </div>

            </div>
          </li>
          <% end %>
        </ul>
      </div>



  </div>
</div>