config/routes.rb
Rails.application.routes.draw do

  resources :categories

  resources :users do
    resources :posts,
    only: [:index, :new, :create]
    resources :comments, only: [ :index, :destroy ]
  end

  resources :posts, only: [:show, :edit, :update, :destroy] do
    resources :votes, only: [:create]
    resources :comments, only: [:create, :destroy ], module: :posts
  end

  resources :comments, only: [ :create, :destroy ] do
    resources :comments, only: [:create, :destroy ], module: :comments
  end

  get 'posts', to: 'posts#all'

  root 'welcome#index'

  get 'login', to: 'sessions#login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DS+L available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_secure_password

  validates :username, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 }

  val_email_reg = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, uniqueness: true, length: { maximum: 105 },
            format: { with: val_email_reg }

  val_pass_reg = /\A(?=.*[a-zA-Z])(?=.*[0-9]).{6,}\z/
                #  | Looks for an arbitrary string followed by a letter
                              #  | Looks for an arbitrary string followed by a number.
                                          # | Ensure there are at least 6 characters

  validates :password, presence: true, length: { minimum: 8, maximum: 25 },
            format: { with: val_pass_reg }

  validates_confirmation_of :password, message: ": Passwords don't match!"
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        flash[:success] = 'User was successfully created.'
        format.html { redirect_to @user }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, flash[:success] = 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div class="well well-danger">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.text_field :password, class: "form-control", placeholder: "Contain 1 number and 1 uppercase" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
  </div>


    <%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="panel panel-default ">
        <div class="panel-heading">
          <div class="btn-group">
              <%= link_to 'Back', user_path(@user), class: "btn btn-default" %>
          </div>
          <h2>Update Profile</h2>
        </div>
          <div class="panel-body">
            <%= render 'form', user: @user %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <div class="col-xs-12">
        <h1 align="center">Users</h1>
        <hr>
        <% @users.each do |user| %>
          <div class="list-group col-xs-12 col-sm-6">
            <%= link_to(user_path(user), class: "list-group-item") do %>
              <div class="media-body">
                <h3><%= user.username %></h3>
                <small><%= user.email %></small>
              </div>


              <div class="media-right" align="center">
                <h3 align="center"><%= user.comments.count %></h3>
                <hr>
                <h6 align="center">Comments</h6>
              </div>
              <div class="media-right" align="center">
                <h3 align="center"><%= user.posts.count %></h3>
                <hr>
                <h6 align="center">Posts</h6>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="panel panel-default">
        <div class="panel-heading">

          <h1>Sign up</h1>
        </div>
        <div class="panel-body">
          <%= render 'form', user: @user %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="btn-group">
            <%= link_to 'Users', users_path, class: "btn btn-default"%>
            <% if logged_in? && @user == current_user %>
              <%= link_to(edit_user_path(@user), class: "btn btn-primary" ) do %>
                Edit Profile | <i class="fa fa-pencil"></i>
              <% end %>
            <% end %>
          </div>
          <h2><%= @user.username.capitalize %>'s Profile</h2>
        </div>

        <div class="panel-body">
          <ul class="list-group">
            <li class="list-group-item">
              Email: <%= @user.email %>
            </li>

              <li class="list-group-item">
                Posts:
                <%= link_to user_posts_path(@user) do %>
                  <span class="badge badge-success"><%= @user.posts.count %></span>
                <% end %>
              </li>
            <li class="list-group-item">
              Comments:
              <%= link_to user_comments_path(@user) do %>
                <span class="badge badge-success"><%= @user.comments.count %></span>
              <% end %>
            </li>
          </ul>
        </div>

        <% if logged_in? && @user == current_user %>
          <div class="panel-footer">
            <%= link_to(user_path(@user), method: :delete,
            data: { confirm: "Are you sure you want to deactivate your account? "},
            class: "btn btn-danger btn-lg") do %>
              Deactivate | <i class="fa fa-trash-o"></i>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>