config/routes.rb
Rails.application.routes.draw do

  resources :categories

  resources :users do
    resources :posts,
    only: [:index, :new, :create]
    resources :comments, only: [ :index, :destroy ]
  end

  resources :posts, only: [:show, :edit, :update, :destroy] do
    resources :votes, only: [:create]
    resources :comments, only: [:create, :destroy ], module: :posts
  end

  resources :comments, only: [ :create, :destroy ] do
    resources :comments, only: [:create, :destroy ], module: :comments
  end

  get 'posts', to: 'posts#all'

  root 'welcome#index'

  get 'login', to: 'sessions#login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DS+L available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :votes, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :post_categories
  has_many :categories, through: :post_categories
  # This sets a default url for img_url
  def img_url(url= "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7G9JTqB8z1AVU-Lq7xLy1fQ3RMO-Tt6PRplyhaw75XCAnYvAYxg")
    self[:img_url] || url
  end

  # This adds up all votes on a Post instance
  def score
    votes.sum(:vote)
  end

  # search code
  def self.search(search)
    where('user.username iLIKE ?', "%#{search}%")
  end

end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
    @commentable = Post.find(params[:post_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def all

    @posts = Post.all.order("created_at ASC").sort_by(&:score).reverse

    # if params[:search]
    #   @posts = Post.search(params[:search]).order("created_at ASC")
    # else
    #   @posts = Post.all.order("created_at ASC").sort_by(&:score).reverse
    # end
  end
  # GET /users/:user_id/posts
  # GET /users/:user_id/posts.json
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.all

    if @posts.count == 0
      redirect_to user_path(@user)
      flash[:danger] = "No posts available to see."
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments.order("comments.created_at DESC")
  end

  # GET /posts/new
  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.new()
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @user = current_user
    @post = @user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id, :link, :img_url, category_ids: [])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_add_post.html.erb
<div class="above">
  <div class="container-table">

    <div class="row vertical-center-row">

      <div class="col-xs-12 col-sm-6 col-sm-offset-3">

        <div class="panel panel-default">


          <div class="panel-heading">
            <div class="pull-right thefa">
              <a href="#">
              <i class="fa fa-times fa-2x"></i>
              </a>
            </div>


              <h1 align="center">Add a post</h1>


          </div>

          <%= form_for([current_user, Post.new], html: { class: "form-horizontal"}) do |p| %>

          <div class="panel-body">
            <div class="form-group">
              <%= p.label :title, class: "col-xs-12 col-sm-2 control-label" %>
              <div class="col-xs-12 col-sm-10">
                <%= p.text_field :title, class: "form-control", placeholder: "Enter a title" %>
              </div>
            </div>

            <div class="form-group">
              <%= p.label :link, class: "col-xs-12 col-sm-2 control-label" %>
              <div class="col-xs-12 col-sm-10">
                <%= p.text_field :link, class: "form-control", placeholder: "Paste link url here" %>
              </div>
            </div>

            <div class="form-group">
              <%= p.label :img_url, "Thumbnail", class: "col-xs-12 col-sm-2 control-label" %>
              <div class="col-xs-12 col-sm-10">
                <%= p.text_field :img_url, class: "form-control", placeholder: "Paste image url here" %>
              </div>
            </div>

            <div class="form-group">
              <%= p.label :body, class: "col-xs-12 col-sm-2 control-label "%>
              <div class="col-xs-12 col-sm-10 ">
                <%= p.text_area :body, rows: "5", class: "form-control", placeholder: "Enter description" %>
              </div>
            </div>
            <!-- select boxes for categories -->
            <div class="form-group">
              <div class="col-xs-12 col-sm-10 ">
                <%= p.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                  <% cb.label(class: "checkbox-inline col-xs-12 col-sm-2 control-label") {cb.check_box(class: "checkbox col-xs-12 col-sm-10") + cb.text } %>
                <% end %>
              </div>
            </div>
            <!-- end select boxes for categories -->
          </div>

          <div class="panel-footer">
            <div class="form-group">
              <div class="col-xs-12 col-sm-10 col-sm-offset-2">
                <%= p.submit "Post", class: "btn btn-success" %>
              </div>
            </div>
          </div>
          <% end %>
        </div>

      </div>
    </div>

  </div>

</div>

app/views/posts/_downvote.html.erb
<!-- form for downvote -->
<%= form_for([downvote,  Vote.new]) do |p| %>
  <!-- This hidden_field adds a -1 vote -->
  <%= p.hidden_field :vote, value: -1 %>
  <%= button_tag(class: "btn btn-default btn-sm btn-bot") do %>
    <i class="fa fa-chevron-down fa-lg"></i>
  <% end %>
<% end %>
<!-- end downvote form -->

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :link %>
    <%= f.text_field :link, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :img_url %>
    <%= f.text_field :img_url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :user_id %>
    <%= f.text_field :user_id, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-success"%>
  </div>
<% end %>

app/views/posts/_posts.html.erb
  <div class="col-xs-12 col-sm-6">

    <div class="panel panel-default">
      <div class="panel-body">
        <div class="media">

          <!-- this is the form style for the upvote downvote buttons a -->
          <div class="media-left">
            <div class="btn-group-vertical btn-group-sm">
                  <%= render partial: "posts/upvote", locals: { upvote: posts } %>

              <button type="button" name="button" class="btn btn-default">
                <%= posts.score %>
              </button>

                  <%= render partial: "posts/downvote", locals: { downvote: posts} %>

            </div>
          </div>
          <!-- end the voting buttons -->
          <!-- main media body -->
          <div class="media-body">
            <!-- image thumbnail for post -->
            <img src="<%= posts.img_url %>" width="70px" height="70px" alt="" class="media-object pull-right">
            <!-- link to show page for post -->
            <%= link_to(post_path(posts)) do %>
            <h2 class="media-heading">
              <%= posts.title %>
            </h2>
            <% end %>
            <!-- end show page link -->

            <!-- header body text & truncated -->
            <%= truncate(posts.body, length: 100, omission: '... (click to see more)') %>
            <br/>
            <!-- time made info -->
            <small>Posted <%= time_ago_in_words(posts.created_at) %> ago.</small>
            <hr>
            <!-- view link button to open link associated with post -->
            <div class="pull-left">
              <%= link_to "View Link", posts.link, class: "btn btn-default btn-xs" %>
              <% posts.categories.each do |category| %>
                <%= link_to category.name, category_path(category), class: "btn btn-info btn-xs" %>

              <% end %>
            </div>

            <!-- edit buttons -->
            <div class="pull-right">

              <% if logged_in? && posts.user_id == current_user.id %>

                <div class="btn-group toggle pull-left">
                  <%= link_to(edit_post_path(posts), class: "btn btn-primary btn-xs") do %>
                    Edit <i class="fa fa-pencil"></i>
                  <% end %>
                  <%= link_to(post_path(posts), method: :delete,
                  data: { confirm: "Are you sure?"}, class: "btn btn-danger btn-xs" ) do %>
                    Delete <i class="fa fa-trash-o"></i>
                  <% end %>
                </div>
                <i class="fa fa-ellipsis-v fa-lg pull-right"></i>
              <% end %>

            </div>
          </div>
          <!-- end media body -->
        </div>

      </div>
    </div>
  </div>

app/views/posts/_upvote.html.erb
<!--  This form_for is passing in two things
 current post, and adding votes to this post
 post is identifying the post you want to add votes to
 post.votes.build is adding the votes to that post
 before I had Vote.new which is adding a new vote in general
 but since the first argument is for post, it understands the relation anyways. -->
<%= form_for([upvote,  Vote.new ]) do |p| %>
  <%= p.hidden_field :vote, value: 1 %>
  <%= button_tag(class: "btn btn-default btn-sm btn-top") do %>
    <i class="fa fa-chevron-up fa-lg"></i>
  <% end %>
<% end %>
<!-- end upvote form -->

app/views/posts/all.html.erb
<div class="container">
  <div class="row">
    <div class="" align="center">
      <a href="#" class="btn btn-success btn-lg above-toggle">Add Post  <i class="fa fa-plus"></i></a>

    </div>

    <hr>
      <%= render partial: "posts/posts", collection: @posts %>

  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="media-left">
            <div class="btn-group">
              <%= link_to 'Back', @post, class: "btn btn-default" %>
            </div>
          </div>
          <h1>Editing Post</h1>
        </div>
        <div class="panel-body">
          <%= render 'form', post: @post %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <% @posts.each do |post| %>
      <div class="col-xs-12 col-sm-6">

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="media">

              <!-- this is the form style for the upvote downvote buttons a -->
              <div class="media-left">
                <div class="btn-group-vertical btn-group-sm">
                      <%= render partial: "posts/upvote", locals: { upvote: post } %>

                  <button type="button" name="button" class="btn btn-default">
                    <%= post.score %>
                  </button>

                      <%= render partial: "posts/downvote", locals: { downvote: post} %>

                </div>
              </div>
              <!-- end the voting buttons -->
              <!-- main media body -->
              <div class="media-body">
                <!-- image thumbnail for post -->
                <img src="<%= post.img_url %>" width="70px" height="70px" alt="" class="media-object pull-right">
                <!-- link to show page for post -->
                <%= link_to(post_path(post)) do %>
                <h2 class="media-heading">
                  <%= post.title %>
                </h2>
                <% end %>
                <!-- end show page link -->

                <!-- header body text & truncated -->
                <%= truncate(post.body, length: 100, omission: '... (click to see more)') %>
                <br/>
                <!-- time made info -->
                <small>Posted <%= time_ago_in_words(post.created_at) %> ago.</small>
                <hr>
                <!-- view link button to open link associated with post -->
                <div class="pull-left">
                  <%= link_to "View Link", post.link, class: "btn btn-default btn-xs" %>
                </div>

                <!-- edit buttons -->
                <div class="pull-right">

                  <% if logged_in? && post.user_id == current_user.id %>

                    <div class="btn-group toggle pull-left">
                      <%= link_to(edit_post_path(post), class: "btn btn-primary btn-xs") do %>
                        Edit <i class="fa fa-pencil"></i>
                      <% end %>
                      <%= link_to(post_path(post), method: :delete,
                      data: { confirm: "Are you sure?"}, class: "btn btn-danger btn-xs" ) do %>
                        Delete <i class="fa fa-trash-o"></i>
                      <% end %>
                    </div>
                    <i class="fa fa-ellipsis-v fa-lg pull-right"></i>
                  <% end %>

                </div>
              </div>
              <!-- end media body -->
            </div>

          </div>
        </div>
      </div>

    <% end %>

  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="media-left">
            <div class="btn-group">
              <%= link_to 'Back', posts_path, class: "btn btn-default" %>
            </div>
          </div>
          <h1>Editing Post</h1>
        </div>
        <div class="panel-body">
          <%= render 'form', post: @post %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="media">

            <div class="media-left">
              <div class="btn-group-vertical btn-group-sm">

                  <%= render partial: "posts/upvote", locals: { upvote: @post } %>
                    <!-- end upvote form -->

                <button type="button" name="button" class="btn btn-default btn-sm">
                  <%= @post.score %>
                </button>

                  <!-- form for downvote -->
                  <%= render partial: "posts/downvote", locals: { downvote: @post } %>
                  <!-- end downvote form -->
              </div>
            </div>

            <div class="media-body">
              <!-- image thumbnail for post -->
              <img src="<%= @post.img_url %>" width="70px" height="70px" alt="" class="media-object pull-right">

              <h2 class="media-heading">
                <%= @post.title %>
              </h2>

              <!-- header body text & truncated -->
              <%= @post.body %>
              <br/>
              <!-- time made info -->
              <small>Posted <%= time_ago_in_words(@post.created_at) %> ago.</small>
              <hr>
              <!-- view link button to open link associated with post -->

              <div class="pull-left">
                <%= link_to "All Posts", posts_path, class: "btn btn-default btn-xs" %>
                <%= link_to "View Link", @post.link, class: "btn btn-default btn-xs" %>
                <% @post.categories.each do |category| %>
                  <%= link_to category.name, category_path(category), class: "btn btn-info btn-xs" %>

                <% end %>
              </div>

              <!-- edit buttons -->
              <div class="pull-right">

                <% if logged_in? && @post.user_id == current_user.id %>

                  <div class="btn-group toggle pull-left">
                    <%= link_to(edit_post_path(@post), class: "btn btn-primary btn-xs") do %>
                      Edit <i class="fa fa-pencil"></i>
                    <% end %>
                    <%= link_to(post_path(@post), method: :delete,
                    data: { confirm: "Are you sure?"}, class: "btn btn-danger btn-xs" ) do %>
                      Delete <i class="fa fa-trash-o"></i>
                    <% end %>
                  </div>
                  <i class="fa fa-ellipsis-v fa-lg pull-right"></i>
                <% end %>

              </div>

            </div>
            <!-- end media body -->
            </div>
            <!-- end media -->
          </div>
          <!-- end panel body -->


          <div class="panel-footer">
            <% if logged_in? %>

              <%= render partial: "comments/form", locals: { commentable: @post } %>

            <% else %>
              <h3>Please log in to make a comment.</h3>

            <% end %>
            <!-- show all post comments -->
            <% if @post.comments.any? %>
              <ul class="list-group">
                <%= render partial: "comments/comments", collection: @comments %>
              </ul>

            <% end %>
            <!-- end show post comments -->

          </div>
        </div>
      </div>
    </div>
  </div>
</div>