config/routes.rb
Rails.application.routes.draw do

  resources :categories

  resources :users do
    resources :posts,
    only: [:index, :new, :create]
    resources :comments, only: [ :index, :destroy ]
  end

  resources :posts, only: [:show, :edit, :update, :destroy] do
    resources :votes, only: [:create]
    resources :comments, only: [:create, :destroy ], module: :posts
  end

  resources :comments, only: [ :create, :destroy ] do
    resources :comments, only: [:create, :destroy ], module: :comments
  end

  get 'posts', to: 'posts#all'

  root 'welcome#index'

  get 'login', to: 'sessions#login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DS+L available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash.html.erb
<% flash.each do |type,msg| %>
  <div class="alert alert-<%= type %> col-xs-10 col-xs-offset-1">
    <%= msg %>
    <a href="#" data-dismiss="alert" class="float-right"><i class="fa fa-times"></i></a>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "[COMMENT_P4]", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Posts", posts_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'All', categories_path %></li>
            <li role="separator" class="divider"></li>
            <% Category.all.each do |category| %>
              <% if category.posts.any? %>
                <li><%= link_to category.name, category_path(category) %></li>
              <% end %>
            <% end %>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Create Category', new_category_path %></li>
          </ul>
        </li>
      </ul>

      <!-- implement searching mech for categories -->
      <!-- <% if (params[:action] == "all" && params[:controller] == "posts") && (Post.count > 1) %>

        <%= form_tag(posts_path, method: :get,  class: "navbar-form navbar-left" ) do %>
          <div class="form-group">
            <%=text_field_tag :search, params[:search], class: "form-control", placeholder: "Search Categories" %>
          </div>

            <%= submit_tag "Search", class: "btn btn-default" %>
        <% end %>
      <% end %> -->
      <!-- end search implementation -->

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>



              <li class="dropdown ">
                <a href="#" class="dropdown-toggle "
                data-toggle="dropdown" role="button"
                aria-haspopup="true" aria-expanded="false">
                  <%= current_user.username %> <span class="caret"></span>
                </a>

                <ul class="dropdown-menu">
                  <li><%= link_to 'Profile', user_path(current_user) %></li>
                  <li><%= link_to 'Posts', user_posts_path(current_user) %></li>
                  <li><%= link_to 'Comments', user_comments_path(current_user) %></li>

                  <li role="separator" class="divider"></li>
                  <li><%= link_to 'Logout', logout_path, method: :delete, class: "btn btn-danger" %></li>
                </ul>
              </li>


        <% else %>

          <div class="btn-group">
            <%= link_to "Sign up", new_user_path, class: "btn btn-default navbar-btn" %>
            <%= link_to "Log in", login_path, class: "btn btn-success navbar-btn" %>
          </div>

        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CommentingAppP4</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
    <%= render 'posts/add_post' %>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/flash' %>
    <%= yield %>
    </div>
  </body>
</html>